"""Add year_level and hsc_subjects to User model

Revision ID: 63bc5b7c03e5
Revises: 
Create Date: 2025-05-12 19:05:43.318925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63bc5b7c03e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('hsc_subjects', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('hsc_subjects')
        batch_op.drop_column('year_level')

    # ### end Alembic commands ###
