"""Add profile fields and remove year_level

Revision ID: d742bd76ad94
Revises: 63bc5b7c03e5
Create Date: 2025-05-13 07:19:19.383408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd742bd76ad94'
down_revision = '63bc5b7c03e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.drop_column('year_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_level', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('bio')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('address')
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###
